[project]
name = "20251-progeficaz-projeto-2-boligura"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "mysql-connector-python>=9.2.0",
    "pytest>=8.3.5",
    "python-dotenv>=1.0.1",
]
